name: "\U0001F41E Bug report"
description: Create a report to help us improve
labels: ['bug: pending triage']
body:
  - type: markdown
    attributes:
      value: |
        "Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. If you're reporting a potential bug with the unexpected report of checkers(tsc / eslint / vue-tsc / ...) Please make sure to run the report with the checker only to ensure the unexpected report is plugin-specified(e.g. run `tsc --noEmit` to check the vanilla reports of typescript), if so, please coming up with an issue and attach the report of vanilla checker. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. Note that if there is expected or unexpected errors, you can run the checker directly to validate if this is plugin related. For example, you can run `tsc --noEmit` or `vue-tsc --noEmit` for `typescript` and `vueTsc` checks.
      placeholder: Expected behavior
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages vite-plugin-checker --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the bug report here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
          required: true
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
