name: Release

on:
  push:
    tags:
      - 'vite-plugin-checker@*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install Dependencies
        run: pnpm i

      - name: PNPM build
        run: |
          pnpm run format
          pnpm run lint
          pnpm run type-check
          pnpm run clean
          pnpm run build
          pnpm run publint
          cp README.md packages/vite-plugin-checker/README.md

      - name: Publish to NPM
        run: pnpm publish --filter vite-plugin-checker --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
